=== re-motion/Trunk-SVN2Git/ObjectBinding/Web.CodeGenerator/DomainSample/mapping.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:m="http://www.re-motion.org/Data/DomainObjects/Mapping/1.0" 
    xmlns:t="http://www.re-motion.org/Data/DomainObjects/Types" 
    elementFormDefault="qualified" 
    attributeFormDefault="unqualified" 
    targetNamespace="http://www.re-motion.org/Data/DomainObjects/Mapping/1.0" 
    xml:lang="en">

  <xs:import namespace="http://www.re-motion.org/Data/DomainObjects/Types" schemaLocation="types.xsd" />

  <xs:element name="mapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="classes" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="class" type="m:classType" maxOccurs="unbounded">

                <xs:key name="propertyKey">
                  <xs:selector xpath="m:properties/m:property | m:properties/m:relationProperty" />
                  <xs:field xpath="@name" />
                </xs:key>

                <xs:unique name="columnUnique">
                  <xs:selector xpath="m:properties/m:property | m:properties/m:relationProperty" />
                  <xs:field xpath="m:column" />
                </xs:unique>

              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="application" type="t:requiredStringType" use="required" />
    </xs:complexType>

    <xs:key name="classKey">
      <xs:selector xpath="m:classes/m:class" />
      <xs:field xpath="@id" />
    </xs:key>

  </xs:element>

  <xs:complexType name="classType">
    <xs:sequence>
      <xs:element name="type" type="t:dotNetType" />
      <xs:element name="entity">
        <xs:complexType>
          <xs:attribute name="name" type="t:requiredStringType" use="required" />
        </xs:complexType>
      </xs:element>
      <xs:element name="storageProviderID" type="t:requiredStringType" />
      <xs:element name="properties">
        <xs:complexType>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="property" type="m:propertyType" />
            <xs:element name="relationProperty" type="m:relationPropertyType">
              <xs:keyref name="oppositeClassToClass" refer="m:classKey">
					 		<xs:selector xpath="." />
							<xs:field xpath="m:oppositeClass" />
 					 </xs:keyref>
            </xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="t:requiredStringType" use="required" />
    <xs:attribute name="baseClass" type="t:requiredStringType" use="optional" />
  </xs:complexType>

  <xs:complexType name="propertyType">
    <xs:sequence>
      <xs:element name="type" type="m:simpleTypeOrDotNetType" />
      <xs:element name="column" type="t:requiredStringType" />
      <xs:element name="nullable" type="xs:boolean" minOccurs="0" />
      <xs:element name="maxLength" type="m:positiveIntType" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="name" type="t:requiredStringType" use="required" />
  </xs:complexType>

  <xs:complexType name="relationPropertyType">
    <xs:choice minOccurs="0">
    	 <xs:sequence>
	    	 <xs:element name="column" type="t:requiredStringType" />
	    	 <xs:element name="oppositeClass" type="t:requiredStringType" minOccurs="0" />
    	 </xs:sequence>	
      <xs:sequence>
        <xs:element name="collectionType" type="t:dotNetType" minOccurs="0" />
        <xs:element name="sortExpression" type="t:requiredStringType" minOccurs="0" />
      </xs:sequence>
    </xs:choice>
    <xs:attribute name="name" type="t:requiredStringType" use="required" />
    <xs:attribute name="relationID" type="t:requiredStringType" use="required" />
    <xs:attribute name="isMandatory" type="xs:boolean" use="required" />
    <xs:attribute name="cardinality" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="one" />
          <xs:enumeration value="many" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:simpleType name="positiveIntType">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="simpleTypeOrDotNetType">
    <xs:union memberTypes="m:simpleType t:dotNetType" />
  </xs:simpleType>

  <xs:simpleType name="simpleType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="boolean" />
      <xs:enumeration value="byte" />
      <xs:enumeration value="date" />
      <xs:enumeration value="dateTime" />
      <xs:enumeration value="decimal" />
      <xs:enumeration value="double" />
      <xs:enumeration value="guid" />
      <xs:enumeration value="int16" />
      <xs:enumeration value="int32" />
      <xs:enumeration value="int64" />
      <xs:enumeration value="single" />
      <xs:enumeration value="string" />
      <xs:enumeration value="binary" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== re-motion/Trunk-SVN2Git/Remotion/ObjectBinding/Web.CodeGenerator/WebSample/mapping.xml
<?xml version="1.0" encoding="UTF-8" ?>
<mapping application="PhoneBook" 
    xmlns="http://www.re-motion.org/Data/DomainObjects/Mapping/1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.re-motion.org/Data/DomainObjects/Mapping/1.0 mapping.xsd">
  <classes>
    <class id="Person">
      <type>DomainSample.Person, DomainSample</type>
      <entity name="Person" />
      <storageProviderID>PhoneBookDB</storageProviderID>
      <properties>
        <property name="FirstName">
          <type>string</type>
          <column>FirstName</column>
          <nullable>true</nullable>
          <maxLength>255</maxLength>
        </property>
        <property name="LastName">
          <type>string</type>
          <column>LastName</column>
          <maxLength>255</maxLength>
        </property>
        <property name="EMailAddress">
          <type>string</type>
          <column>EMailAddress</column>
          <nullable>true</nullable>
          <maxLength>255</maxLength>
        </property>

			<!-- Unidirectional relation -->
        <relationProperty name="Location" relationID="LocationToPerson" cardinality="one" isMandatory="false">
          <column>Location</column>
          <oppositeClass>Location</oppositeClass>  
        </relationProperty>
        
        <!-- Bidirectional relation -->
        <relationProperty name="PhoneNumbers" relationID="PersonToPhoneNumber" cardinality="many" isMandatory="false">
          <collectionType>DomainSample.PhoneNumberCollection, DomainSample</collectionType>
          <sortExpression>CountryCode ASC, AreaCode ASC, Number ASC, Extension ASC</sortExpression>
        </relationProperty>

      </properties>
    </class>

    <class id="Location">
      <type>DomainSample.Location, DomainSample</type>
      <entity name="Location" />
      <storageProviderID>PhoneBookDB</storageProviderID>
      <properties>
        <property name="Name">
          <type>string</type>
          <column>Name</column>
          <maxLength>255</maxLength>
        </property>
        <property name="ZipCode">
          <type>string</type>
          <column>ZipCode</column>
          <nullable>true</nullable>
          <maxLength>12</maxLength>
        </property>
        <property name="City">
          <type>string</type>
          <column>City</column>
          <nullable>true</nullable>
          <maxLength>255</maxLength>
        </property>
        <property name="Street">
          <type>string</type>
          <column>Street</column>
          <nullable>true</nullable>
          <maxLength>255</maxLength>
        </property>

			<!-- Property with an enumerated type -->
        <property name="Country">
          <type>DomainSample.Country, DomainSample</type>
          <column>Country</column>
          <nullable>true</nullable>
        </property>
      </properties>
    </class>

    <class id="PhoneNumber">
      <type>DomainSample.PhoneNumber, DomainSample</type>
      <entity name="PhoneNumber" />
      <storageProviderID>PhoneBookDB</storageProviderID>
      <properties>
        <property name="CountryCode">
          <type>string</type>
          <column>CountryCode</column>
          <nullable>true</nullable>
          <maxLength>6</maxLength>
        </property>
        <property name="AreaCode">
          <type>string</type>
          <column>AreaCode</column>
          <nullable>true</nullable>
          <maxLength>6</maxLength>
        </property>
        <property name="Number">
          <type>string</type>
          <column>Number</column>
          <maxLength>80</maxLength>
        </property>
        <property name="Extension">
          <type>string</type>
          <column>Extension</column>
          <nullable>true</nullable>
          <maxLength>6</maxLength>
        </property>
        
        <!-- Bidirectional relation -->
        <relationProperty name="Person" relationID="PersonToPhoneNumber" cardinality="one" isMandatory="true">
          <column>Person</column>
        </relationProperty>
        
      </properties>
    </class>
  </classes>
</mapping>
